### ISSUE TITLE
no

### ISSUE THREAD

**Issue by charagarlnad** [TheStr3ak5/neoholyC#1]
this is not ok streaks cease

**Comment by TheStr3ak5** [comment]
@charagarlnad I accept your suggestion for an improvement in the parser mechanism, I do think leaving the symbol table tier on the first stage CMOS RAM leaves a lot of room for improvements and memory wise its not the best solution, but we got to remember that mapping such an structure would take at least a 53 level red-black tree with each node having at least 12 hash maps embeeded that would make things pretty much enbearable.

Having this into account, I will take your suggestion as a priority in the roadmap of the project, but I cant ensure that we will have the luck of seeing it implemented until the next aeon

**Comment by charagarlnad** [comment]
i hate you
